preload = /home/junius/Pictures/house-garden.png
preload = /home/junius/Pictures/garden.png
preload = /home/junius/Pictures/dead-robot.jpg
preload = /home/junius/Pictures/samurai.jpg
wallpaper = ,/home/junius/Pictures/garden.png
 
